urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Example:
	# (r'^pvtmsg/', include('pvtmsg.foo.urls')),
	(r'^i18n/', include('django.conf.urls.i18n')),

	# Uncomment the admin/doc line below to enable admin documentation:
	# (r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	(r'^admin/', include(admin.site.urls)),
	(r'^captcha/', include('captcha.urls')),
	(r'^login/', 'django.contrib.auth.views.login'),
	(r'^registration/', 'auth.views.registration1'),
	(r'^registration2/', 'auth.views.registration2'),
	(r'^changepassword/', 'auth.views.changepassword'),
	(r'^registration_keys/', 'auth.views.registration_keys'),
	(r'^get_public_key/', 'userprofile.views.get_publickey'),
	(r'^confirm/(?P<user>\w+)/(?P<code>\w+)$', 'auth.views.confirm_email'),
	(r'^messages/(?P<directory>\w+)/', 'messages.views.messages'),
	(r'^message/', 'messages.views.message'),
	(r'^readmessage/', 'messages.views.readmessage'),
	(r'^newmessage/', 'messages.views.newmessage'),
	(r'^sendmessage/', 'messages.views.sendmessage'),
	(r'^savedraft/', 'messages.views.savedraft'),
	(r'^deletemessage/', 'messages.views.deletemessage'),
	(r'^emptytrash/', 'messages.views.emptytrash'),
	(r'^friends/', 'userprofile.views.friends'), #temporaneao
	(r'^friendship/', 'userprofile.views.friend'), #temporaneao
	(r'^search_friend/', 'userprofile.views.searchfriend'), #temporaneao
	(r'^myprofile/', 'userprofile.views.profile'), #temporaneao
	(r'^add_friend/', 'userprofile.views.addfriend'), #temporaneao
	(r'^directories/', 'messages.views.directories'), #temporaneao
	(r'^directory/', 'messages.views.directory'), #temporaneao
)

import os
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,'show_indexes': False}),
    )

messages/models.py
import uuid
from django.db import models
from userprofile.models import *
from django.conf import settings
from uuidfield import UUIDField

# Create your models here.
class Directory(models.Model):
	name = models.CharField(max_length=30,blank=False)
	slugfied = models.SlugField(null=True,blank=True)
	relation = models.ForeignKey('self',null=True,blank=True,verbose_name="child_of")
	def save(self, *args, **kwargs):
		self.slugfied = slugify(self.name)
		super(Directory, self).save(*args, **kwargs)
	def __unicode__(self):
		return self.name
	class Meta:
		ordering = ['name']

class Attachment(models.Model):
	uuid = UUIDField(auto=True)
	name = models.CharField(max_length=50)
	file = models.FileField(upload_to=settings.MEDIA_ATTACHMENTS,null=True,blank=True) #sistemare
	type = models.CharField(max_length=30)
	createdDate = models.DateTimeField(auto_now_add=True)
	def __unicode__(self):
		return self.name
	class Meta:
		ordering = ['name']

class Message(models.Model):
	uuid = UUIDField(auto=True)
	fromUsr = models.ForeignKey('userprofile.UserProfile',related_name="from_user",verbose_name="from User",null=True,blank=True)
	toUsr = models.ForeignKey('userprofile.UserProfile',related_name="to_user",verbose_name="to User",null=True,blank=True)
	subject = models.CharField(max_length=200,null=True,blank=True)
	text = models.TextField(null=True,blank=True)
	notes = models.TextField(null=True,blank=True)
	uuid_sent = models.TextField(null=True,blank=True)
	uuid_outbox = models.TextField(null=True,blank=True)
	lamportSign = models.TextField(null=True,blank=True)
	saveKey = models.IntegerField(max_length=2,null=True,blank=True)
	createdDate = models.DateTimeField(auto_now_add=True)
	readDate = models.DateTimeField(null=True,blank=True)
	directory = models.ForeignKey(Directory,null=True,blank=True)
	draft = models.BooleanField()
	deleted = models.BooleanField()
	important = models.BooleanField()
	relation = models.ForeignKey('self',null=True,blank=True,verbose_name="message related")
	attachments = models.ManyToManyField(Attachment,null=True,blank=True)
	key_version = models.CharField(max_length=5)
	def __unicode__(self):
		return "%s %s %s"%(self.fromUsr.user.username,self.toUsr.user.username,self.subject)
	class Meta:
		ordering = ['-createdDate']
	

messages/forms.py
from django import forms
from django.utils.translation import ugettext_lazy
from userprofile.models import UserProfile

class SendMessageForm(forms.Form):
	recipient = forms.ModelChoiceField(queryset='', empty_label=None,label=ugettext_lazy("RECIPIENT"),help_text=ugettext_lazy('HELP_TEXT_RECIPIENT'))
	subject = forms.CharField(label=ugettext_lazy("SUBJECT"),max_length=50,required=False,help_text=ugettext_lazy('HELP_TEXT_SUBJECT'),widget=forms.TextInput(attrs={'class': 'notrequired'}))
	message = forms.CharField(label=ugettext_lazy("MESSAGE"),required=True,help_text=ugettext_lazy('HELP_TEXT_MESSAGE'),widget=forms.Textarea(attrs={'class': 'required'}))
	important = forms.BooleanField(label=ugettext_lazy("IMPORTANT"),required=False,help_text=ugettext_lazy('HELP_TEXT_IMPORTANT'))
	sent = forms.BooleanField(label=ugettext_lazy("SAVE_SENT"),required=False,help_text=ugettext_lazy('HELP_TEXT_SAVE_SENT'))
	relation = forms.CharField(label=ugettext_lazy("RELATION"))
	oldid = forms.CharField(label=ugettext_lazy("OLDID"))
	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None)
		super(SendMessageForm, self).__init__(*args, **kwargs)
		user = self.request.user
		self.fields['recipient'].queryset = UserProfile.objects.get(user=user).friends.all()

messages/views.py
# Create your views here.
import json,hashlib,random,string
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext as _
from django.http import HttpResponseForbidden,HttpResponse
from django.template import RequestContext
from models import *
from forms import *
from userprofile.models import UserProfile,Transmissionkey
from django.conf import settings
from django.core import serializers

@login_required()
def newmessage(request):
	form = SendMessageForm(initial={'sent':True},request=request)
	return render_to_response('messages/new.html',{
		'form': form
	},context_instance = RequestContext(request))



@login_required()
def sendmessage(request):
	result=json.dumps({'result':'ko'})
	if request.method == 'GET':
		transmission_key_num=request.GET.get('transmissionKey');
		encapsulated_text=request.GET.get('text');
		key=UserProfile.objects.get(user=request.user)
		
		try:
			transmission_key=UserProfile.objects.get(user=request.user).transmission_keys.get(version=settings.KEY_VERSION,number=transmission_key_num).key;
			from Crypto.Cipher import AES
			m = hashlib.sha256()
			m.update(transmission_key)
			transmission_key_sha=m.digest()
			decryptor = AES.new(transmission_key_sha, AES.MODE_CBC)
			message = decryptor.decrypt(encapsulated_text.replace('-','+').replace('_','/').decode("base64"))
			message=message[message.find('{'):(message.rfind('}')+1)]
			message=json.loads(message)
			if (request.user.username==message.get('from','')):
				user=UserProfile.objects.get(user=request.user)
				if message.get('oldid','') !='':
					try:
						msd=user.messages.get(uuid__exact=message.get('oldid',''),draft=True)
						msd.delete()
					except Message.DoesNotExist:
						pass
				try:
					friend=UserProfile.objects.get(user__username__exact=message.get('to',''))
					m=Message.objects.create(fromUsr=user,toUsr=friend,subject=message.get('subject',''),text=message.get('message',''),important=message.get('important',0),key_version=settings.KEY_VERSION)
					friend.messages.add(m)
					if message.get('save_as_sent',False):
						ms=Message.objects.create(fromUsr=user,toUsr=friend,subject=message.get('subject',''),text=message.get('saved_sent',''),saveKey=message.get('saved_sent_key',0),important=message.get('important',0),key_version=settings.KEY_VERSION,uuid_outbox=m.uuid)
						user.messages.add(ms)
						m.sent_uuid=ms.uuid
						m.save()
					result=json.dumps({'result':'ok'})
				except UserProfile.DoesNotExist:
					pass
		except Transmissionkey.DoesNotExist:
			pass
	return HttpResponse(result)

@login_required()
def savedraft(request):
	result=json.dumps({'result':'ko'})
	if request.method == 'GET':
		transmission_key_num=request.GET.get('transmissionKey');
		encapsulated_text=request.GET.get('text');
		key=UserProfile.objects.get(user=request.user)
		
		try:
			transmission_key=UserProfile.objects.get(user=request.user).transmission_keys.get(version=settings.KEY_VERSION,number=transmission_key_num).key;
			from Crypto.Cipher import AES
			m = hashlib.sha256()
			m.update(transmission_key)
			transmission_key_sha=m.digest()
			decryptor = AES.new(transmission_key_sha, AES.MODE_CBC)
			message = decryptor.decrypt(encapsulated_text.replace('-','+').replace('_','/').decode("base64"))
			message=message[message.find('{'):(message.rfind('}')+1)]
			
			message=json.loads(message)
			result=message.get('message','')
			if (request.user.username==message.get('from','')):
				user=UserProfile.objects.get(user=request.user)
				friend=UserProfile.objects.get(user__username__exact=message.get('to',''))
				if message.get('oldid','') !='':
					try:
						msd=user.messages.get(uuid__exact=message.get('oldid',''),draft=True)
						msd.delete()
					except Message.DoesNotExist:
						pass
				try:
					ms=Message.objects.create(fromUsr=user,toUsr=friend,subject=message.get('subject',''),text=message.get('message',''),draft=True,saveKey=message.get('saved_sent_key',0),important=message.get('important',0),key_version=settings.KEY_VERSION)
					user.messages.add(ms)
					result=json.dumps({'result':'ok','message_uuid':ms.uuid})
				except UserProfile.DoesNotExist:
					pass
		except Transmissionkey.DoesNotExist:
			pass
	return HttpResponse(result)
	
@login_required()
def deletemessage(request):
	result='ko'
	if request.method == 'GET':
		idmessage=request.GET.get('idmessage','')
		definitely=request.GET.get('definitely',0)
		if idmessage is not None and len(idmessage)>5:
			try:
				m=UserProfile.objects.get(user=request.user).messages.get(uuid__exact=idmessage,deleted=False)
				m.deleted=True
				m.save()
				result='ok'
			except Message.DoesNotExist:
				pass
			if definitely=='1':
				try:
					m=UserProfile.objects.get(user=request.user).messages.get(uuid__exact=idmessage,deleted=True).delete()
					result='ok'
				except Message.DoesNotExist:
					pass
	return HttpResponse(result)

@login_required()
def emptytrash(request):
	result='ko'
	try:
		UserProfile.objects.get(user=request.user).messages.filter(deleted=True).delete()
		result='ok'
	except Message.DoesNotExist:
		pass
	return HttpResponse(result)

@login_required()
def message(request):
	result=json.dumps({'result':'ko'})
	transmission_key_num=random.randint(0,settings.TRANSMISSION_NUM_KEYS-1)
	transmission_key=UserProfile.objects.get(user=request.user).transmission_keys.get(version=settings.KEY_VERSION,number=transmission_key_num).key;
	from Crypto.Cipher import AES
	m = hashlib.sha256()
	m.update(transmission_key)
	transmission_key_sha=m.digest()
	encryptor = AES.new(transmission_key_sha, AES.MODE_CBC)
	idmessage=request.GET.get('idmessage','')
	try:
		message=UserProfile.objects.get(user=request.user).messages.get(uuid__exact=idmessage)
		messageToSend=json.dumps({'uuid':message.uuid,'from':message.fromUsr.user.username,'to':message.toUsr.user.username,'subject':message.subject,'text':message.text,'notes':message.notes,'saveKey':message.saveKey,'important':message.important,'relation':message.relation,'key_version':message.key_version,'created_date':str(message.createdDate),'read_date':str(message.readDate),'uuid_sent':message.uuid_sent,'uuid_outbox':message.uuid_outbox})
		messageToSend=("".join(random.sample(string.letters+string.digits, 16)))+messageToSend
		messageToSend=messageToSend+((16-len(messageToSend)%16)*'@')
		message = encryptor.encrypt(messageToSend).encode("base64").replace('+','-').replace('/','_')
		result=json.dumps({'result':'ok','data':{'transmission_key_num':transmission_key_num,'message':message}})
	except Message.DoesNotExist:
		pass
	return HttpResponse(result)

@login_required()
def readmessage(request):
	form = SendMessageForm(initial={'sent':True},request=request)
	return render_to_response('messages/message.html',{
		'form': form
	},context_instance = RequestContext(request))

@login_required()
def messages(request,directory):
	if directory=='inbox':
		messages=UserProfile.objects.get(user=request.user).messages.filter(toUsr__user=request.user,deleted=False,directory=None)
	elif directory=='sent':
		messages=UserProfile.objects.get(user=request.user).messages.filter(fromUsr__user=request.user,draft=False,deleted=False,directory=None)
	elif directory=='drafts':
		messages=UserProfile.objects.get(user=request.user).messages.filter(fromUsr__user=request.user,draft=True,deleted=False,directory=None)
	elif directory=='trash':
		messages=UserProfile.objects.get(user=request.user).messages.filter(deleted=True)
	else:
		messages=UserProfile.objects.get(user=request.user).messages.filter(draft=False,deleted=False,directory__slugfied=directory)
	return render_to_response('messages/home.html',{'messages':messages,'directory':directory,'user':request.user})

@login_required()
def directories(request):
	if request.user.is_authenticated():
		try:
			directories=UserProfile.objects.get(user=request.user).directories.all()
		except UserProfile.DoesNotExist:
			return HttpResponseForbidden(_('YOU_HAVE_TO_LOGIN'))
	return render_to_response('directories/home.html',{'directories':directories})

@login_required()
def directory(request):
	id=request.GET.get('id')
	name=request.GET.get('name')
	action=request.GET.get('action')
	result='ko'
	try:
		user=UserProfile.objects.get(user=request.user)
	except UserProfile.DoesNotExist:
		return HttpResponseForbidden(_('YOU_HAVE_TO_REGISTER'))
	if request.user.is_authenticated():
		if action is not None:
			if action in ('rename','add','delete'):
				if id is not None and name is not None:
					if len(id)>2 and len(name)>2 and action == 'rename':
						try:
							directory=user.directories.get(slugfied=id)
							directory.name=name
							directory.save()
							result='ok'
						except Directory.DoesNotExist:
							return HttpResponseForbidden(_('THE_FOLDER_DOESNT_EXIST'))
				if name is not None:
					if len(name)>2 and action == 'add':
						if user.directories.filter(name=name).count()==0:
							directory=Directory.objects.create(name=name)
							user.directories.add(directory)
							result='ok'
				if id is not None:
					if len(id)>0 and action == 'delete':
						try:
							directory=user.directories.get(slugfied=id)
							if request.GET.get('delete_files')=='yes':
								Message.objects.filter(directory=directory).update(deleted=True)
								Message.objects.filter(directory=directory).update(directory='')
							else:
								Message.objects.filter(directory=directory).update(directory='')
							directory.delete()
							result='ok'
						except Directory.DoesNotExist:
							return HttpResponseForbidden(_('THE_FOLDER_DOESNT_EXIST'))
	return HttpResponse(result)

templates/messages/home.html
{% load i18n %}
{{user}}
{{directory}}
<ul>
{% for message in messages %}
<li>{{message.fromUsr.user.username}}, {{message.subject}}, {{message.uuid}}</li>
{% endfor %}
</ul>

templates/messages/message.html
{% load i18n %}<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<script src="{{MEDIA_URL}}jscript/libs/jquery.js" type="text/javascript"></script>
		<script src="{{MEDIA_URL}}jscript/libs/jquery.json.js" type="text/javascript"></script>
		<script src="{{MEDIA_URL}}jscript/libs/jquery.cookie.js" type="text/javascript" ></script>
		<script src="{{MEDIA_URL}}jscript/libs/swfobject.js" type="text/javascript"></script>
		<script src="{{MEDIA_URL}}jscript/libs/downloadify.min.js" type="text/javascript"></script>
		<script src="{{MEDIA_URL}}jscript/libs/privatemessage.js" type="text/javascript"></script>
		<script type="text/javascript">
			
			
			$(document).ready(function() {
				var errors =[
					'{% trans "GENERIC_ERROR_TRY_LATER" %}',
					'{% trans "YOU_HAVE_TO_LOGIN" %}',
					'{% trans "GET_PUBLIC_KEY_PROBLEM" %}',
					'{% trans "AES_KEY_NOT_CORRECT" %}',
					'{% trans "NOT_CORRECT_KEY_VERSION" %}',
					'{% trans "KEY_FROM_ANOTHER_DOMAIN" %}',
					'{% trans "RSA_ENCRYPTION_PROBLEM" %}',
					'{% trans "YOU_CANT_SENT_EMPTY_MESSAGE" %}',
					'{% trans "YOU_HAVE_TO_SELECT_A_RECIPIENT" %}',
					'{% trans "YOU_HAVE_TO_SELECT_YOUR_PERSONAL_KEY" %}',
					'{% trans "YOU_HAVE_TO_SELECT_YOUR_PERSONAL_KEY_PASSWORD" %}',
					'{% trans "PROBLEMS_SENDING_MESSAGE_TRY_AGAIN" %}',
					'{% trans "PROBLEMS_SAVING_MESSAGE_TRY_AGAIN" %}'
					];
				var idmessage = pvtmsg.getUrlParam('idmessage');
				if (pvtmsg.getUrlParam('idmessage')!=''){
					var reader = new FileReader();
					reader.onload = function(){
						pvtmsg.readMessage('{{MEDIA_URL}}',this.result,$('#pwdkey').val(),idmessage,errors);
					};
					reader.readAsText($('#filekey')[0].files[0]);
				}
			
				$("#send").click(function(){
					var data={'recipient':$('#id_recipient :selected').text(),
							'subject':$('#id_subject').val(),
							'important':($('#id_important').is(':checked'))?1:0,
							'oldid':$('#id_oldid').val(),
							'relation':$('#id_relation').val(),
							'message':$('#id_message').val(),
							'save_as_sent':($('#id_sent').is(':checked'))?1:0
							};
					
					if (data['recipient']!=''){
						if (data['message']!=''){
							if ($('#filekey')[0].files[0]!='undefined'){
								if ($('#pwdkey').val()!='') {
									var reader = new FileReader();
									reader.onload = function(){
										pvtmsg.sendMessage('{{MEDIA_URL}}',this.result,$('#pwdkey').val(),data,errors);
									};
									reader.readAsText($('#filekey')[0].files[0]);
								} else alert(errors[10]);
							} else alert(errors[9]);
						} else alert(errors[7]);
					} else alert (errors[8]);
				});
				
				
				$("#savedraft").click(function(){
					var data={'recipient':$('#id_recipient :selected').text(),
							'subject':$('#id_subject').val(),
							'important':($('#id_important').is(':checked'))?1:0,
							'oldid':$('#id_oldid').val(),
							'relation':$('#id_relation').val(),
							'message':$('#id_message').val(),
							'save_as_sent':($('#id_sent').is(':checked'))?1:0
							};
					

					if (data['message']!=''){
						if ($('#filekey')[0].files[0]!='undefined'){
							if ($('#pwdkey').val()!='') {
								var reader = new FileReader();
								reader.onload = function(){
									pvtmsg.saveDraft('{{MEDIA_URL}}',this.result,$('#pwdkey').val(),data,errors);
								};
								reader.readAsText($('#filekey')[0].files[0]);
							} else alert(errors[10]);
						} else alert(errors[9]);
					} else alert(errors[7]);
				});
			});
		</script>
	</head>
	<body>
		{{ form.as_p }}
		<input type="text" name="pwdkey" id="pwdkey">
		<input type="file" name="filekey" id="filekey">
		<input type="button" value="{% trans 'SEND' %}" id="send"/>
		<input type="button" value="{% trans 'SAVE_DRAFT' %}" id="savedraft"/>
	</body>
</html>

templates/messages/new.html
{% load i18n %}<?xml version="1.0"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<script src="{{MEDIA_URL}}jscript/libs/jquery.js" type="text/javascript"></script>
		<script src="{{MEDIA_URL}}jscript/libs/jquery.json.js" type="text/javascript"></script>
		<script src="{{MEDIA_URL}}jscript/libs/jquery.cookie.js" type="text/javascript" ></script>
		<script src="{{MEDIA_URL}}jscript/libs/swfobject.js" type="text/javascript"></script>
		<script src="{{MEDIA_URL}}jscript/libs/downloadify.min.js" type="text/javascript"></script>
		<script src="{{MEDIA_URL}}jscript/libs/privatemessage.js" type="text/javascript"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				var errors =[
					'{% trans "GENERIC_ERROR_TRY_LATER" %}',
					'{% trans "YOU_HAVE_TO_LOGIN" %}',
					'{% trans "GET_PUBLIC_KEY_PROBLEM" %}',
					'{% trans "AES_KEY_NOT_CORRECT" %}',
					'{% trans "NOT_CORRECT_KEY_VERSION" %}',
					'{% trans "KEY_FROM_ANOTHER_DOMAIN" %}',
					'{% trans "RSA_ENCRYPTION_PROBLEM" %}',
					'{% trans "YOU_CANT_SENT_EMPTY_MESSAGE" %}',
					'{% trans "YOU_HAVE_TO_SELECT_A_RECIPIENT" %}',
					'{% trans "YOU_HAVE_TO_SELECT_YOUR_PERSONAL_KEY" %}',
					'{% trans "YOU_HAVE_TO_SELECT_YOUR_PERSONAL_KEY_PASSWORD" %}',
					'{% trans "PROBLEMS_SENDING_MESSAGE_TRY_AGAIN" %}',
					'{% trans "PROBLEMS_SAVING_MESSAGE_TRY_AGAIN" %}',
					'{% trans "PROBLEMS_READING_MESSAGE_TRY_AGAIN" %}'
					];
				
				$("#send").click(function(){
					var data={'recipient':$('#id_recipient :selected').text(),
							'subject':$('#id_subject').val(),
							'important':($('#id_important').is(':checked'))?1:0,
							'oldid':$('#id_oldid').val(),
							'relation':$('#id_relation').val(),
							'message':$('#id_message').val(),
							'save_as_sent':($('#id_sent').is(':checked'))?1:0
							};
					
					if (data['recipient']!=''){
						if (data['message']!=''){
							if ($('#filekey')[0].files[0]!='undefined'){
								if ($('#pwdkey').val()!='') {
									var reader = new FileReader();
									reader.onload = function(){
										pvtmsg.sendMessage('{{MEDIA_URL}}',this.result,$('#pwdkey').val(),data,errors);
									};
									reader.readAsText($('#filekey')[0].files[0]);
								} else alert(errors[10]);
							} else alert(errors[9]);
						} else alert(errors[7]);
					} else alert (errors[8]);
				});
				
				
				$("#savedraft").click(function(){
					var data={'recipient':$('#id_recipient :selected').text(),
							'subject':$('#id_subject').val(),
							'important':($('#id_important').is(':checked'))?1:0,
							'oldid':$('#id_oldid').val(),
							'relation':$('#id_relation').val(),
							'message':$('#id_message').val(),
							'save_as_sent':($('#id_sent').is(':checked'))?1:0
							};
					

					if (data['message']!=''){
						if ($('#filekey')[0].files[0]!='undefined'){
							if ($('#pwdkey').val()!='') {
								var reader = new FileReader();
								reader.onload = function(){
									pvtmsg.saveDraft('{{MEDIA_URL}}',this.result,$('#pwdkey').val(),data,errors);
								};
								reader.readAsText($('#filekey')[0].files[0]);
							} else alert(errors[10]);
						} else alert(errors[9]);
					} else alert(errors[7]);
				});
			});
		</script>
	</head>
	<body>
		{{ form.as_p }}
		<input type="text" name="pwdkey" id="pwdkey">
		<input type="file" name="filekey" id="filekey">
		<input type="button" value="{% trans 'SEND' %}" id="send"/>
		<input type="button" value="{% trans 'SAVE_DRAFT' %}" id="savedraft"/>
	</body>
</html>